### ISSUE TITLE
Linux Pre-Compilations Tied to Prior Version of Boost

### ISSUE THREAD

**Issue by sporkius-alt** [Dollar-coin/Dollar#1]
When attempting to run the shared compiled files for Linux on Debian the following error is presented:

`sudo ./dollard
./dollard: error while loading shared libraries: libboost_system.so.1.65.1: cannot open shared object file: No such file or directory`

The current version of Boost is 1.67.0.1, 1.65.1 is no longer available on package lists for Debian (and likely Ubuntu, although i have not confirmed this). The distributed versions should be updated to be based off of Boost 1.67.0.1. Although it is likely that unless distributed with all dependencies they too will have issues with this.

**Comment by Dollar-coin** [comment]
Hello sporkius, I invite you to follow instructions from this link https://github.com/Dollar-coin/Dollar/wiki/How-to-open-Dollar-Core-on-Linux

**Comment by sporkius-alt** [comment]
> Hello sporkius, I invite you to follow instructions from this link https://github.com/Dollar-coin/Dollar/wiki/How-to-open-Dollar-Core-on-Linux

Unfortunately those instructions are broken as well. You may want to update that page to reflect the PPA from bitcoin no longer having a valid release file. I ended up using the below code to compile a working version of the berkeley4.8db 

```
wget http://download.oracle.com/berkeley-db/db-4.8.30.zip

    unzip db-4.8.30.zip

    cd db-4.8.30

    cd build_unix/

    ../dist/configure --prefix=/usr/local --enable-cxx

    make

    make install`
```

**Comment by Dollar-coin** [comment]
Thank you for your feedback
